define(['rwcore'], function(rwcore){

  var _templates = {
    StdForm : { location: '/Templates/Forms/StdForm.html?version=6.0', value : null },
    StdList : { location: '/Templates/Lists/StdList.html?version=6.0', value : null }, 
    StdPickList : { location: '/Templates/Lists/StdPicklistTemplate.html?version=6.0', value : null }, 
    textField : { location: '/Templates/Fields/TextField.html?version=6.0',value : null },
    richTextField : { location: '/Templates/Fields/RichTextField.html?version=6.0',value : null },
    emailField : { location: '/Templates/Fields/EMailField.html?version=6.0',value : null },
    imageField : { location: '/Templates/Fields/ImageField.html?version=6.0',value : null },
    phoneField : { location: '/Templates/Fields/PhoneField.html?version=6.0',value : null },
    AddressField : { location: '/Templates/Fields/AddressField.html?version=6.0',value : null },
    dateField : { location: '/Templates/Fields/DateField.html?version=6.0',value : null },
    numberField : { location: '/Templates/Fields/NumberField.html?version=6.0',value : null },
    CaptchaField : { location: '/Templates/Fields/CaptchaField.html?version=6.0',value : null },
    StdROView : { location: '/Templates/Forms/StdReadOnlyView.html?version=6.0',value : null },
    StdLDView : { location: '/Templates/Patterns/StdListDetailView.html?version=6.1',value : null },
    StdMDView : { location: '/Templates/Patterns/StdMasterDetailView.html?version=6.0', value : null },
    drilldownTemplate : { location: '/Templates/Fields/drilldownTemplate.html?version=6.0', value : null },
    ActionBarTemplate : { location: '/Templates/Patterns/ActionBarTemplate.html?version=6.0', value : null },
    home : { location: '/Templates/home/Homepage.html?version=6.0',value : null },
    upsertForm : { location: '/Templates/Forms/UpsertForm.html?version=6.0',value : null },
    paypalTemplate : { location: '/Templates/custom/PaypalTemplate.html?version=6.0',value : null },
    pickLaunchButton : { location: '/Templates/Fields/pickLaunchButton.html?version=6.0',value : null },
    pickField : { location: '/Templates/Fields/pickField.html?version=6.0',value : null },
    StdDynamicPickList : { location: '/Templates/Lists/StdDynamicPickList.html?version=6.0',value : null },
    ImpConTemplate : { location: '/Templates/Patterns/ImpConTemplate.html?version=6.0',  value : null },
    RStreamList : { location: '/Templates/Lists/RefStreamList.html?version=6.0',  value : null },
    HomePageTitleSummary : { location: '/Templates/home/HomePageTitleSummary.html?version=6.0',  value : null },
    HomePageReferralChartPanel : { location: '/Templates/home/HomePageReferralChartPanel.html?version=6.0',value : null },
    HomePageNewReferralsList : { location: '/Templates/Lists/HomePageNewReferralsList.html?version=6.0',value : null },
    SimpleList : { location: '/Templates/Lists/SimpleList.html?version=6.0',value : null },
    SimpleView : { location: '/Templates/Forms/SimpleForm.html?version=6.0',value : null },
    moneyField : { location: '/Templates/Fields/MoneyField.html?version=6.0',value : null },
    ReferralInbox : { location: '/Templates/home/ReferralInbox.html?version=6.0',value : null },
    ReferralInboxUnread : { location: '/Templates/home/ReferralInboxUnread.html?version=6.0',value : null },
    pickContacts : { location: '/Templates/phone/pickContacts.html?version=6.0',value : null },
    phonehome : { location: '/Templates/home/phonehome.html?version=6.0',value : null },
    StdSummaryDetailView : { location: '/Templates/Patterns/StdSummaryDetailView.html?version=6.0',value : null },
    URLField : { location: '/Templates/Fields/URLField.html?version=6.0',value : null },
    StdThumbNailList : { location: '/Templates/Lists/StdThumbNailList.html?version=6.0',value : null },
    ReferralOutbox : { location: '/Templates/home/ReferralOutbox.html?version=6.0',value : null },
    ProfileEditorView : { location: '/Templates/SocialProfile/ProfileEditorView.html?version=6.0',value : null },
    TextAreaField : { location: '/Templates/Fields/TextAreaField.html?version=6.0',value : null },
    BulletListField : { location: '/Templates/Fields/BulletListField.html?version=6.0',value : null },
    Snippets : { location: '/Templates/Patterns/Snippets.html?version=6.0',value : null },
    PreferencesForm : { location: '/Templates/SocialProfile/PreferencesForm.html?version=6.0',value : null },
    AppletMenuTemplate : { location: '/Templates/Patterns/AppletMenuTemplate.html?version=6.0',value : null },
    PhonePartnerList : { location: '/Templates/phone/PhonePartnerList.html?version=6.0',value : null },
    PhonePartnerProfile : { location: '/Templates/phone/PhonePartnerProfile.html?version=6.0',value : null },
    ContactListPhone : { location: '/Templates/phone/ContactListPhone.html?version=6.0',value : null },
    CreateReferralForm : { location: '/Templates/Referral/CreateReferralForm.html?version=6.0',value : null },
    BooleanField : { location: '/Templates/Fields/BooleanField.html?version=6.0',value : null },
    ReferralSentConfirmation : { location: '/Templates/Referral/ReferralSentConfirmation.html?version=6.0',value : null },
    ViewReferralForm : { location: '/Templates/Referral/ViewReferralForm.html?version=6.0',value : null },
    ReferralMenuTemplate : { location: '/Templates/Referral/ReferralMenuTemplate.html?version=6.0',value : null },
    InBoxList : { location: '/Templates/Referral/InBoxList.html?version=6.0',value : null },
    AcceptReferralConfirmation : { location: '/Templates/Referral/AcceptReferralConfirmation.html?version=6.0',value : null },
    ConfirmReferralConfirmation : { location: '/Templates/Referral/ConfirmReferralConfirmation.html?version=6.0',value : null },
    ConvertReferralConfirmation : { location: '/Templates/Referral/ConvertReferralConfirmation.html?version=6.0',value : null },
    ArchiveReferralConfirmation : { location: '/Templates/Referral/ArchiveReferralConfirmation.html?version=6.0',value : null },
    UnArchiveReferralConfirmation : { location: '/Templates/Referral/UnArchiveReferralConfirmation.html?version=6.0',value : null },
    NoRecordForm : { location: '/Templates/Forms/NoRecordForm.html?version=6.0', value : null },
    NoRecordViewBar : { location: '/Templates/Patterns/NoRecordViewBar.html?version=6.0',value : null },
    OutBoxList : { location: '/Templates/Referral/OutBoxList.html?version=6.0',value : null },
    OutBoxReferralForm : { location: '/Templates/Referral/OutBoxReferralForm.html?version=6.0',value : null },
    PhotoGalleryThumbs : { location: '/Templates/Forms/PhotoGalleryThumbs.html?version=6.0',value : null },
    PhotoGalleryShow : { location: '/Templates/Forms/PhotoGalleryShow.html?version=6.0',value : null },
    ProfileDisplayView : { location: '/Templates/SocialProfile/ProfileDisplayView.html?version=6.0',  value : null },
    Testimonials : { location: '/Templates/Forms/Testimonials.html?version=6.0',value : null },
    LinkedInProfile : { location: '/Templates/SocialProfile/LinkedInProfile.html?version=6.0',value : null },
    TestimonialsDisplay : { location: '/Templates/Forms/TestimonialsDisplay.html?version=6.0',  value : null },
    PhotoGalleryThumbsNoEdit : { location: '/Templates/Forms/PhotoGalleryThumbsNoEdit.html?version=6.0',value : null },
    MasterTwoDetail : { location: '/Templates/Patterns/MasterTwoDetail.html?version=6.0',value : null },
    PartnerReferralInbox : { location: '/Templates/Referral/PartnerReferralInbox.html?version=6.0',value : null },
    PartnerReferralOutbox : { location: '/Templates/Referral/PartnerReferralOutBox.html?version=6.0',value : null },
    HiddenField : { location: '/Templates/Fields/HiddenField.html?version=6.0',value : null },
    ProfilePrintView : { location: '/Templates/SocialProfile/ProfilePrintView.html?version=6.0',value : null },
    ReferralProspectSummaryForm : { location: '/Templates/Referral/ReferralProspectSummaryForm.html?version=6.0',value : null },
    MashupView : { location: '/Templates/Patterns/MashupView.html?version=6.0',value : null },
    MultiColumnList : { location: '/Templates/Lists/MultiColumnList.html?version=6.0',value : null },
    StdMDMCView : { location: '/Templates/Patterns/StdMDMCView.html?version=6.0',value : null },
    LNRadioList : { location: '/Templates/Lists/LNRadioList.html?version=6.0',value : null },
    ProfileNavigation : { location: '/Templates/Forms/ProfileNavigation.html?version=6.0',value : null },
    LeftNavSummaryDetailView : { location: '/Templates/Patterns/LeftNavSummaryDetailView.html?version=6.0',value : null },
    LeftNavMDMCView : { location: '/Templates/Patterns/LeftNavMDMCView.html?version=6.0',value : null },
    PickCreateForm : { location: '/Templates/Forms/PickCreateForm.html?version=6.0',value : null },
    changePasswordTemplate : { location: '/Templates/custom/changePasswordTemplate.html?version=6.0',value : null },
    PasswordField : { location: '/Templates/Fields/PasswordField.html?version=6.0',value : null },
    changePaypalIDTemplate : { location: '/Templates/custom/changePaypalIDTemplate.html?version=6.0',value : null },
    contextHelp : { location: '/Help/contextHelp.html?version=6.0',value : null },
    PhonePickContactList : { location: '/Templates/phone/PhonePickContactList.html?version=6.0',value : null },
    PhoneUpsertForm : { location: '/Templates/phone/PhoneUpsertForm.html?version=6.0',value : null },
    CreateReferralCustomQ : { location: '/Templates/phone/CreateReferralCustomQ.html?version=6.0',value : null },
    PhoneStdView : { location: '/Templates/phone/PhoneStdView.html?version=6.0',value : null },
    PhonePageNoViewBar : { location: '/Templates/phone/PhonePageNoViewBar.html?version=6.0',value : null },
    PhoneStdForm : { location: '/Templates/phone/PhoneStdForm.html?version=6.0',value : null },
    PhoneStdFormRefer : { location: '/Templates/phone/PhoneStdFormRefer.html?version=6.0',value : null },
    ContactList : { location: '/Templates/Lists/ContactList.html?version=6.0',value : null },
    PhoneAppletMenu : { location: '/Templates/phone/PhoneAppletMenu.html?version=6.0',value : null },
    PhonePageUpsert : { location: '/Templates/phone/PhonePageUpsert.html?version=6.0',value : null },
    CompositeTextField : { location: '/Templates/Fields/CompositeTextField.html?version=6.0',value : null },
    pickFieldComposite : { location: '/Templates/Fields/pickFieldComposite.html?version=6.0',value : null },
    ConfirmDelete : { location: '/Templates/Patterns/ConfirmDelete.html?version=6.0',value : null },
    ConfirmImport : { location: '/Templates/Patterns/ConfirmImport.html?version=6.0',value : null },
    ConfirmBilling : { location: '/Templates/Patterns/ConfirmBilling.html?version=6.0',value : null },
    Eula : { location: '/Templates/home/TermsOfUse.html?version=6.0',value : null },
    ListSectionDetailView : { location: '/Templates/Patterns/ListSectionDetailView.html?version=6.0',value : null },
    CollapseForm : { location: '/Templates/Forms/CollapseForm.html?version=6.0', value : null },
    StdFormNarrow : { location: '/Templates/Forms/StdFormNarrow.html?version=6.0', value : null },
    ImportProgress : { location: '/Templates/Patterns/ImportProgress.html?version=6.0', value : null },
    TestimonialsQuoteEdit : { location: '/Templates/Forms/TestimonialsQuoteEdit.html?version=6.0',value : null },
    WizardUpsertForm : { location: '/Templates/Forms/WizardUpsertForm.html?version=6.0',value : null },
    WizardUpsertView : { location: '/Templates/Patterns/WizardUpsertView.html?version=6.0',value : null },
    EnrichProgress : { location: '/Templates/Patterns/EnrichProgress.html?version=6.0',value : null },
    CSVExportProgress : { location: '/Templates/Patterns/CSVExportProgress.html?version=6.0',value : null },
    ConfirmEnrich : { location: '/Templates/Patterns/ConfirmEnrich.html?version=6.0',value : null },
    CreateReferralWizardForm : { location: '/Templates/Referral/CreateReferralWizardForm.html?version=6.0',value : null },
    RadioButtons : { location: '/Templates/Fields/RadioButtons.html?version=6.0',value : null },
    MultiCheckBoxes : { location: '/Templates/Fields/MultiCheckBoxes.html?version=6.0',value : null },
    MultiCheckBoxes_Search : { location: '/Templates/Fields/MultiCheckBoxes_Search.html?version=6.0',value : null },
    WizardUpsertFormNarrow : { location: '/Templates/Forms/WizardUpsertFormNarrow.html?version=6.0',value : null },
    WizardUpsertFormNarrowRefType : { location: '/Templates/Forms/WizardUpsertFormNarrowRefType.html?version=6.0',value : null },
    CreateReferralWizardFormP2P : { location: '/Templates/Referral/CreateReferralWizardFormP2P.html?version=6.0',value : null },
    ReferralInboxP2P : { location: '/Templates/ReferralP2P/ReferralInboxP2P.html?version=6.0',value : null },
    ReferralInboxInvite : { location: '/Templates/ReferralP2P/ReferralInboxInvite.html?version=6.0',value : null },
    ReferralOutboxP2P : { location: '/Templates/ReferralP2P/ReferralOutboxP2P.html?version=6.0',value : null },
    ReferralOutboxInvite : { location: '/Templates/ReferralP2P/ReferralOutboxInvite.html?version=6.0',value : null },
    ViewReferralFormP2P : { location: '/Templates/ReferralP2P/ViewReferralFormP2P.html?version=6.0',value : null },
    AcceptReferralConfirmationNoArch : { location: '/Templates/Referral/AcceptReferralConfirmationNoArch.html?version=6.0',value : null },
    ViewReferralFormUnreadProspect : { location: '/Templates/Referral/ViewReferralFormUnreadProspect.html?version=6.0',value : null },
    ReferralViewBarTemplate : { location: '/Templates/Referral/ReferralViewBarTemplate.html?version=6.0',value : null },
    ViewReferralFormInvite : { location: '/Templates/ReferralP2P/ViewReferralFormInvite.html?version=6.0',value : null },
    OutBoxReferralFormP2P : { location: '/Templates/ReferralP2P/OutBoxReferralFormP2P.html?version=6.0',value : null },
    OutBoxReferralFormInvite : { location: '/Templates/ReferralP2P/OutBoxReferralFormInvite.html?version=6.0',value : null },
    PartnerReferralInboxP2P : { location: '/Templates/ReferralP2P/PartnerReferralInboxP2P.html?version=6.0',value : null },
    PartnerReferralInboxInvite : { location: '/Templates/ReferralP2P/PartnerReferralInboxInvite.html?version=6.0',value : null },
    PartnerReferralOutBoxP2P : { location: '/Templates/ReferralP2P/PartnerReferralOutBoxP2P.html?version=6.0',value : null },
    PartnerReferralOutBoxInvite : { location: '/Templates/ReferralP2P/PartnerReferralOutBoxInvite.html?version=6.0',value : null },
    ContactListPrivate : { location: '/Templates/Lists/ContactListPrivate.html?version=6.0',value : null },
    StdFormContact : { location: '/Templates/Forms/StdFormContact.html?version=6.0',value : null },
    StdFormPartner : { location: '/Templates/Forms/StdFormPartner.html?version=6.0',value : null },
    StdFormContactPartner : { location: '/Templates/Forms/StdFormContactPartner.html?version=6.0',value : null },
    ContactListPrivatePhone : { location: '/Templates/phone/ContactListPrivatePhone.html?version=6.0',value : null },
    PhoneStdFormContact : { location: '/Templates/phone/PhoneStdFormContact.html?version=6.0',value : null },
    CollapseFormNarrow : { location: '/Templates/Forms/CollapseFormNarrow.html?version=6.0', value : null },
    PhonePageUpsertNext : { location: '/Templates/phone/PhonePageUpsertNext.html?version=6.0',value : null },
    PhoneStdFormContactPartner : { location: '/Templates/phone/PhoneStdFormContactPartner.html?version=6.0',value : null },
    UpsertFormNarrow : { location: '/Templates/Forms/UpsertFormNarrow.html?version=6.0',value : null },
    AllMembersList : { location: '/Templates/Lists/AllMembersList.html?version=6.1',value : null },
    StdFormNarrowPub : { location: '/Templates/Forms/StdFormNarrowPub.html?version=6.0',value : null },
    StdFormMember : { location: '/Templates/Forms/StdFormMember.html?version=6.0',value : null },
    PhoneStdMember : { location: '/Templates/phone/PhoneStdMember.html?version=6.1',value : null },
    PhoneMemberProfile : { location: '/Templates/phone/PhoneMemberProfile.html?version=6.0',value : null },
    PhoneMemberList : { location: '/Templates/phone/PhoneMemberList.html?version=6.0',value : null },
    InvitationSentConfirmation : { location: '/Templates/Referral/InvitationSentConfirmation.html?version=6.0',value : null },
    MessageSentConfirmation : { location: '/Templates/Referral/MessageSentConfirmation.html?version=6.0',value : null },
    PhoneStdViewList : { location: '/Templates/phone/PhoneStdViewList.html?version=6.0',value : null },
    StdFormPlain : { location: '/Templates/Forms/StdFormPlain.html?version=6.0',value : null },
    WizardUpsertViewShopping : { location: '/Templates/Patterns/WizardUpsertViewShopping.html?version=6.0',value : null },
    RecommendationsList : { location: '/Templates/Lists/RecommendationsList.html?version=6.0',value : null },
    MasterDetailViewNarrow : { location: '/Templates/Patterns/MasterDetailViewNarrow.html?version=6.0',value : null },
    SpecialtiesMasterPartner : { location: '/Templates/Forms/SpecialtiesMasterPartner.html?version=6.0',value : null },
    WebNavPanel : { location: '/Templates/Patterns/WebNavPanel.html?version=6.0',value : null },
    SecondTierNavBar : { location: '/Templates/Patterns/SecondTierNavBar.html?version=6.0',value : null },
    DashBoard : { location: '/Templates/home/DashBoard.html?version=6.0',value : null },
    RecommendationsListUser : { location: '/Templates/Lists/RecommendationsListUser.html?version=6.0',value : null },  
    SpecialtiesMasterUser : { location: '/Templates/Forms/SpecialtiesMasterUser.html?version=6.0',value : null },
    StdSummaryChartView : { location: '/Templates/Patterns/StdSummaryChartView.html?version=6.0',value : null },
    LeftNavSummaryChartView : { location: '/Templates/Patterns/LeftNavSummaryChartView.html?version=6.0',value : null },
    ContactActionBarTemplate : { location: '/Templates/Patterns/ContactActionBarTemplate.html?version=6.0',value : null },
    RadioButtonsDynamic : { location: '/Templates/Fields/RadioButtonsDynamic.html?version=6.0',value : null },
    PlainForm : { location: '/Templates/Forms/PlainForm.html?version=6.0',value : null },
    CriteriaMapList : { location: '/Templates/Lists/CriteriaMapList.html?version=6.0',value : null },
    ChapterList : { location: '/Templates/Lists/ChapterList.html?version=6.0',value : null },
    ChapterDisplayView : { location: '/Templates/Patterns/ChapterDisplayView.html?version=6.0',value : null },
    ChapterHomeForm : { location: '/Templates/Forms/ChapterHomeForm.html?version=6.0',value : null },
    ChapterFormNarrow : { location: '/Templates/Forms/ChapterFormNarrow.html?version=6.0',value : null },
    ChapterMemberList : { location: '/Templates/Lists/ChapterMemberList.html?version=6.0',value : null },
    PhoneChapterList : { location: '/Templates/phone/PhoneChapterList.html?version=6.0',value : null },
    PhoneChapterProfile : { location: '/Templates/phone/PhoneChapterProfile.html?version=6.0',value : null },
    PhoneChapterMaster : { location: '/Templates/phone/PhoneChapterMaster.html?version=6.0',value : null },
    PhoneMasterDetailView : { location: '/Templates/phone/PhoneMasterDetailView.html?version=6.0',value : null },
    PhoneNavPanel : { location: '/Templates/phone/PhoneNavPanel.html?version=6.0',value : null },
    StdTiles : { location: '/Templates/Forms/StdTiles.html?version=6.0',value : null },
    STN_phonehome : { location: '/Templates/STN/STN_phonehome.html?version=6.0',value : null },
    EventList : { location: '/Templates/Lists/EventList.html?version=6.0',value : null },
    TimeField : { location: '/Templates/Fields/TimeField.html?version=6.0',value : null },
    EventExpectedExpandList : { location: '/Templates/Lists/EventExpectedExpandList.html?version=6.0',value : null },
    AttendenceChart : { location: '/Templates/Patterns/AttendenceChart.html?version=6.0',value : null },
    ChapterDashBoardView : { location: '/Templates/Patterns/ChapterDashBoardView.html?version=6.0',value : null },
    ListMapView : { location: '/Templates/Patterns/ListMapView.html?version=6.0',value : null },
    EventFormNarrow : { location: '/Templates/Forms/EventFormNarrow.html?version=6.0',value : null },
    AttendeeMember : { location: '/Templates/Lists/AttendeeMember.html?version=6.0',value : null },
    CheckedInConfirmation_Self : { location: '/Templates/Patterns/CheckedInConfirmation_Self.html?version=6.0',value : null },
    CheckedInConfirmation_Other : { location: '/Templates/Patterns/CheckedInConfirmation_Other.html?version=6.0',value : null },
    CheckedOutConfirmation_Other : { location: '/Templates/Patterns/CheckedOutConfirmation_Other.html?version=6.0',value : null },
    StdExpandableChildList : { location: '/Templates/Lists/StdExpandableChildList.html?version=6.0',value : null },
    LinkedInTiles : { location: '/Templates/Forms/LinkedInTiles.html?version=6.0',value : null },
    STN_HomePageView : { location: '/STN/Templates/Views/STN_HomePageView.html?version=6.3',value : null },
    STN_BannerMessage : { location: '/STN/Templates/Forms/STN_BannerMessage.html?version=6.0',value : null },
    STN_WebNavPanel : { location: '/STN/Templates/Other/STN_WebNavPanel.html?version=6.0',value : null },
    QualificationsForm : { location: '/Templates/SocialProfile/QualificationsForm.html?version=6.0',value : null },
    QualificationsFormDisplay : { location: '/Templates/SocialProfile/QualificationsFormDisplay.html?version=6.0',value : null },
    ProfileDisplayMapView : { location: '/Templates/SocialProfile/ProfileDisplayMapView.html?version=6.0',value : null },
    BasicForm : { location: '/Templates/Forms/BasicForm.html?version=6.0', value : null },
    STN_StdFormContactPartner : { location: '/STN/Templates/Forms/STN_StdFormContactPartner.html?version=6.0',value : null }, 
    AddGuestConfirmation : { location: '/Templates/Patterns/AddGuestConfirmation.html?version=6.0',value : null },
    ChapterDashBoardViewChart : { location: '/Templates/Patterns/ChapterDashBoardViewChart.html?version=6.0',value : null },
    STN_PhoneHomePageTitleSummary : { location: '/STN/Templates/Phone/STN_PhoneHomePageTitleSummary.html?version=6.0',value : null },
    PhoneContextNavPanel : { location: '/Templates/phone/PhoneContextNavPanel.html?version=6.0',value : null },
    ConfirmJoinChapter : { location: '/Templates/Patterns/ConfirmJoinChapter.html?version=6.0',value : null },
    AttendeeMemberNoAct : { location: '/Templates/Lists/AttendeeMemberNoAct.html?version=6.0',value : null },
    STN_speakerInviteMessage : { location: '/STN/Templates/Other/STN_speakerInviteMessage.html?version=6.0',value : null },
    SpeakersList : { location: '/Templates/Lists/SpeakersList.html?version=6.0',value : null },
    SpeakerForm : { location: '/Templates/Forms/SpeakerForm.html?version=6.0',value : null },
    STN_HomePageUserProfile : { location: '/STN/Templates/Other/STN_HomePageUserProfile.html?version=6.1',value : null },
    STN_EventHomeList : { location: '/STN/Templates/Lists/STN_EventHomeList.html?version=6.0',value : null },
    STN_HomePageTitleSummary : { location: '/STN/Templates/Other/STN_HomePageTitleSummary.html?version=6.1',value : null },
    STN_HomePageReferralStats : { location: '/STN/Templates/Other/STN_HomePageReferralStats.html?version=6.0',value : null },
    LeftNavTilesDetailView : { location: '/Templates/Patterns/LeftNavTilesDetailView.html?version=6.0',value : null },
    InvitedMemberList : { location: '/Templates/Lists/InvitedMemberList.html?version=6.0',value : null },
    CheckedInInvalid : { location: '/Templates/Patterns/CheckedInInvalid.html?version=6.0',value : null },
    DateTimeField : { location: '/Templates/Fields/DateTimeField.html?version=6.0',value : null },
    STN_ChapterListDetailView : { location: '/STN/Templates/Views/STN_ChapterListDetailView.html?version=6.0',value : null },
    WizardAssocSnippet : { location: '/Templates/Patterns/WizardAssocSnippet.html?version=6.0',value : null },
    CheckedInPositionError : { location: '/Templates/Patterns/CheckedInPositionError.html?version=6.0',value : null },
    LeftNavSummaryDetailViewIFrame : { location: '/Templates/Patterns/LeftNavSummaryDetailViewIFrame.html?version=6.0',value : null },
    SocialNetworkLogin : { location: '/Templates/SocialProfile/SocialNetworkLogin.html?version=6.0',value : null },
    SocialNetworkIdentity : { location: '/Templates/SocialProfile/SocialNetworkIdentity.html?version=6.0',value : null },
    PhoneEventMaster : { location: '/Templates/phone/PhoneEventMaster.html?version=6.1',value : null },
    SpeakerFormNarrow : { location: '/Templates/Forms/SpeakerFormNarrow.html?version=6.0',value : null },
    speakerEventList : { location: '/Templates/Lists/speakerEventList.html?version=6.0',value : null },
    mainAdmin : { location: '/Templates/admin/mainAdmin.html?version=6.0',value : null },
    chartAdmin : { location: '/Templates/admin/chartAdmin.html?version=6.0',value : null },
    savedCharts : { location: '/Templates/admin/savedCharts.html?version=6.0',value : null },
    UpdateStatusConfirmation : { location: '/Templates/Referral/UpdateStatusConfirmation.html?version=6.0',value : null },
    UpdateStatusConfirmationDone : { location: '/Templates/Referral/UpdateStatusConfirmationDone.html?version=6.0',value : null },
    AcceptInvitationConfirmation : { location: '/Templates/Referral/AcceptInvitationConfirmation.html?version=6.0',value : null },
    WizardUpsertFormRefStatus : { location: '/Templates/Forms/WizardUpsertFormRefStatus.html?version=6.0',value : null },
    ForwardReferralWizardForm : { location: '/Templates/Referral/ForwardReferralWizardForm.html?version=6.0',value : null },
    WizardUpsertFormRefStatusConfirm : { location: '/Templates/Forms/WizardUpsertFormRefStatusConfirm.html?version=6.0',value : null },
    LeftSecondTierNavSummaryDetailView : { location: '/Templates/Patterns/LeftSecondTierNavSummaryDetailView.html?version=6.0',value : null },
    LeaderboardMade : { location: '/Templates/Forms/LeaderboardMade.html?version=6.0',value : null },
    SearchView : { location: '/Templates/Patterns/SearchView.html?version=6.0',value : null },
    SearchForm : { location: '/Templates/Forms/SearchForm.html?version=6.0',value : null },
    ConfirmSS_Save_Prompt : { location: '/Templates/Patterns/ConfirmSS_Save_Prompt.html?version=6.0',value : null },
    ConfirmSS_Save : { location: '/Templates/Patterns/ConfirmSS_Save.html?version=6.0',value : null },
    ConfirmSS_Delete:  { location: '/Templates/Patterns/ConfirmSS_Delete.html?version=6.0',value : null },
    ConfirmSS_Hide:  { location: '/Templates/Patterns/ConfirmSS_Hide.html?version=6.0',value : null },
    systemMetrics : { location: '/Templates/admin/systemMetrics.html?version=6.0',value : null },
    AwardList : { location: '/Templates/Lists/AwardList.html?version=6.0',value : null },
    BusinessHomeForm : { location: '/Templates/Forms/BusinessHomeForm.html?version=6.0',value : null },
    EmailTemplateForm : { location: '/Templates/Forms/EmailTemplateForm.html?version=6.0',value : null },
    ImageForm : { location: '/Templates/Forms/ImageForm.html?version=6.0',value : null },
    ImageList : { location: '/Templates/Lists/ImageList.html?version=6.0',value : null },
    SpeakerStatsFormNarrow : { location: '/Templates/Forms/SpeakerStatsFormNarrow.html?version=6.0',value : null },
    SpeakerSummaryChartView:  { location: '/Templates/Patterns/SpeakerSummaryChartView.html?version=6.0',value : null },
    RatingStarField : { location: '/Templates/Fields/RatingStarField .html?version=6.0',value : null },
    AllEventList : { location: '/Templates/Lists/AllEventList.html?version=6.0',value : null },
    EventFormAll : { location: '/Templates/Forms/EventFormAll.html?version=6.0',value : null },
    ConfirmJoinMeeting : { location: '/Templates/Patterns/ConfirmJoinMeeting.html?version=6.0',value : null },
    ConfirmLeaveMeeting : { location: '/Templates/Patterns/ConfirmLeaveMeeting.html?version=6.0',value : null },
    BusinessDirectoryHome : { location: '/Templates/Patterns/BusinessDirectoryHome.html?version=6.0',value : null },
    ListMapViewBizDirectory : { location: '/Templates/Patterns/ListMapViewBizDirectory.html?version=6.0',value : null },
    BusDirectoryDetailForm : { location: '/Templates/Forms/BusDirectoryDetailForm.html?version=6.0',value : null },
    ListViewBizDirectory : { location: '/Templates/Patterns/ListViewBizDirectory.html?version=6.0',value : null },
    BusinessDirectoryList : { location: '/Templates/Lists/BusinessDirectoryList.html?version=6.0',value : null },
    BusinessDirectoryEditView : { location: '/Templates/Patterns/BusinessDirectoryEditView.html?version=6.0',value : null },
    PartyThumbNailTile : { location: '/Templates/Lists/PartyThumbNailTile.html?version=6.0',value : null },
    ConfirmBusSearchZip : { location: '/Templates/Patterns/ConfirmBusSearchZip.html?version=6.0',value : null },
    MyEventList : { location: '/Templates/Lists/MyEventList.html?version=6.0',value : null },
    MyEventListPhone : { location: '/Templates/phone/MyEventList.html?version=6.0',value : null },
    BusinessPickList : { location: '/Templates/Lists/BusinessPickList.html?version=6.0',value : null },
    LeaderBoardSummaryDetailView : { location: '/Templates/Patterns/LeaderBoardSummaryDetailView.html?version=6.0',value : null },
    LeaderBoardFormLikeMe : { location: '/Templates/Forms/LeaderBoardFormLikeMe.html?version=6.0',value : null },
    LeaderBoardFormPowerPartners : { location: '/Templates/Forms/LeaderBoardFormPowerPartners.html?version=6.0',value : null },
    LeaderBoardMissingData : { location: '/Templates/Forms/LeaderBoardMissingData.html?version=6.0',value : null },
    PhoneEventFormNarrow : { location: '/Templates/phone/PhoneEventFormNarrow.html?version=6.0',value : null },
    PhoneAllEventList : { location: '/Templates/phone/PhoneAllEventList.html?version=6.0',value : null },
    PhoneMeetingAttendeeList : { location: '/Templates/phone/PhoneMeetingAttendeeList.html?version=6.0',value : null },
    PhoneMeetingAttendeeListNoAct : { location: '/Templates/phone/PhoneMeetingAttendeeListNoAct.html?version=6.0',value : null },
    OutBox3rdPartnerList : { location: '/Templates/Referral/OutBox3rdPartnerList.html?version=6.0',value : null },
    ContactListNoRelation : { location: '/Templates/Lists/ContactListNoRelation.html?version=6.0',value : null },
    ContactListNoRelationPhone : { location: '/Templates/phone/ContactListNoRelationPhone.html?version=6.0',value : null },
    PublicProfileForm : { location: '/Templates/SocialProfile/PublicProfileForm.html?version=6.0',value : null },
    MasterDetailSearchListView : { location: '/Templates/Patterns/MasterDetailSearchListView.html?version=6.0',value : null },
    AttendeeFloater : { location: '/Templates/Lists/AttendeeFloater.html?version=6.0',value : null },
    AttendeeNewGuest : { location: '/Templates/Lists/AttendeeNewGuest.html?version=6.0',value : null },
    AttendeeFloaterNoAct : { location: '/Templates/Lists/AttendeeFloaterNoAct.html?version=6.0',value : null },
    AttendeeNewGuestNoAct : { location: '/Templates/Lists/AttendeeNewGuestNoAct.html?version=6.0',value : null },
    PhoneMemberListPP : { location: '/Templates/phone/PhoneMemberListPP.html?version=6.2',value : null },
    STN_PhoneEventHomeList : { location: '/STN/Templates/Phone/STN_PhoneEventHomeList.html?version=6.0',value : null },
    STN_MissingInfo : { location: '/STN/Templates/Other/STN_MissingInfo.html?version=6.0',value : null },
    STN_BoxScoreNewMembers : { location: '/STN/Templates/Other/STN_BoxScoreNewMembers.html?version=6.0',value : null },
    STN_BoxScoreNewPowerPartners : { location: '/STN/Templates/Other/STN_BoxScoreNewPowerPartners.html?version=6.1',value : null },
    TenantList : { location: '/Templates/Lists/TenantList.html?version=6.0',value : null },
    ChapterMeetingAttendeeListNoAct : { location: '/Templates/Lists/ChapterMeetingAttendeeListNoAct.html?version=6.1',value : null },    
    PowerCenterListDetailView : { location: '/Templates/Patterns/PowerCenterListDetailView.html?version=6.1',value : null },
    MembersDrillList : { location: '/Templates/Lists/MembersDrillList.html?version=6.0',value : null },
    BadgeInlineScore : { location: '/Templates/badges/BadgeInlineScore.html?version=6.0',value : null },
    BadgeInlineRole : { location: '/Templates/badges/BadgeInlineRole.html?version=6.0',value : null },
    BadgeInvitations : { location: '/Templates/badges/BadgeInvitations.html?version=6.0',value : null },
    BadgeAttendance : { location: '/Templates/badges/BadgeAttendance.html?version=6.1',value : null },
    BadgeReferrals: { location: '/Templates/badges/BadgeReferrals.html?version=6.0',value : null },

    BadgeLeadAmbassador: { location: '/Templates/badges/BadgeLeadAmbassador.html?version=6.0',value : null },
    BadgeAssociateAmbassador: { location: '/Templates/badges/BadgeAssociateAmbassador.html?version=6.0',value : null },
    BadgeGenius: { location: '/Templates/badges/BadgeGenius.html?version=6.0',value : null },
    AllMembersListBadges : { location: '/Templates/Lists/AllMembersListBadges.html?version=6.2',value : null },
    PhoneMemberListBadges : { location: '/Templates/phone/PhoneMemberListBadges.html?version=6.1',value : null },
    PhoneMemberProfileBadges : { location: '/Templates/phone/PhoneMemberProfileBadges.html?version=6.1',value : null },
    StdFormMemberBadges : { location: '/Templates/Forms/StdFormMemberBadges.html?version=6.1',value : null },

    STN_HomePageMyBadges : { location: '/STN/Templates/Other/STN_HomePageMyBadges.html?version=6.0',value : null },
    STN_BoxScoreWebProfileHits: { location: '/STN/Templates/Other/STN_BoxScoreWebProfileHits.html?version=6.0',value : null },
    ReferralInboxMessage : { location: '/Templates/home/ReferralInboxMessage.html?version=6.0',value : null },
    ReferralOutboxMessage: { location: '/Templates/home/ReferralOutboxMessage.html?version=6.0',value : null },
    ReferralInboxAnnouncement: { location: '/Templates/home/ReferralInboxAnnouncement.html?version=6.0',value : null },
    
    BadgeRegionalAmbassador: { location: '/Templates/badges/BadgeRegionalAmbassador.html?version=6.0',value : null },

    };

    var underscoreTemplate = _.template;

    _.template = function (templateName, data, settings) {

        var f  = _templates[templateName];

        if ( _.isUndefined(f)) {
            return underscoreTemplate(templateName, data, settings);
        }
        else {                 
            if ( _.isNull(f.value) )
                f.value = rwcore.getTemplate(f.location);
            return underscoreTemplate(f.value, data, settings);
        }
        
    };

    function findTemplate(templateName) {
        return templateName;
    };

    var baseTemplates = {
        origTemplateFn : underscoreTemplate,
        fields : {
            text: 'textField',
            string: 'textField',
            email: 'emailField',
            img: 'imageField',
            phone: 'phoneField',
            date: 'dateField',
            number: 'numberField',
            money : 'moneyField',
            url : 'URLField',
            pick: 'pickField',
            document: 'TextAreaField',
            bulletList: 'BulletListField',
            boolean : 'BooleanField',
            time: 'TimeField',
            integer : 'numberField',
            Captcha : 'CaptchaField',
            hidden : 'HiddenField',
            password: 'PasswordField',
            composite: 'CompositeTextField',
            pickComposite: 'pickFieldComposite',
            radio: '',
            datetime: 'DateTimeField',
            multicheckbox:'',
            multicheckbox_search:'',
            address:'AddressField',
            rating:'RatingStarField'
        },

        StdForm: function() { return findTemplate('StdForm');}, 
        StdList: function() { return  findTemplate('StdList');}, 
        StdPickList: function() { return  findTemplate('StdPickList');},
        textField: function() { return  findTemplate('textField');},
        richTextField: function() { return  findTemplate('richTextField');},
        emailField: function() { return  findTemplate('emailField');},
        imageField: function() { return  findTemplate('imageField');},
        phoneField: function() { return  findTemplate('phoneField');},
        AddressField: function() { return  findTemplate('AddressField');},
        dateField: function() { return  findTemplate('dateField');},
        numberField: function() { return  findTemplate('numberField');},
        CaptchaField : function() { return  findTemplate('CaptchaField');},
        StdROView : function() { return  findTemplate('StdROView');},
        StdLDView: function() { return  findTemplate('StdLDView');},
        StdMDView: function() { return  findTemplate('StdMDView');},
        drilldownTemplate : function() { return findTemplate('drilldownTemplate');},
        ActionBarTemplate: function() { return  findTemplate('ActionBarTemplate');},
        home: function() { return  findTemplate('home');},
        upsertForm: function() { return findTemplate('upsertForm');},
        paypalTemplate: function() { return  findTemplate('paypalTemplate');},
        pickLaunchButton: function() { return findTemplate('pickLaunchButton');},
        pickField: function() { return findTemplate('pickField');},
        StdDynamicPickList: function() { return findTemplate('StdDynamicPickList');},
        ImpConTemplate : function() { return  findTemplate('ImpConTemplate');},
        RStreamList: function() { return findTemplate('RStreamList');},
        HomePageTitleSummary: function() { return findTemplate('HomePageTitleSummary');},
        HomePageReferralChartPanel: function() { return findTemplate('HomePageReferralChartPanel');},
        HomePageNewReferralsList: function() { return findTemplate('HomePageNewReferralsList');},
        SimpleList : function() { return findTemplate('SimpleList');},
        SimpleView: function() { return  findTemplate('SimpleView');},
        moneyField : function() { return  findTemplate('moneyField');},
        ReferralInbox: function() { return  findTemplate('ReferralInbox');},    
        ReferralInboxUnread: function() { return  findTemplate('ReferralInboxUnread');},
        pickContacts : function() { return  findTemplate('pickContacts');},
        phonehome : function() { return  findTemplate('phonehome');},
        StdSummaryDetailView : function() { return  findTemplate('StdSummaryDetailView');},
        URLField : function() { return  findTemplate('URLField');},
        StdThumbNailList: function() { return findTemplate('StdThumbNailList');},
        ReferralOutbox: function() { return findTemplate('ReferralOutbox');},
        ProfileEditorView: function() { return findTemplate('ReferralOutbox');},
        TextAreaField: function() { return findTemplate('TextAreaField');},
        BulletListField: function() { return findTemplate('BulletListField');},
        Snippets: function() { return findTemplate('Snippets');},
        PreferencesForm: function() { return findTemplate('PreferencesForm');},
        AppletMenuTemplate: function() { return findTemplate('AppletMenuTemplate');},
        PhonePartnerList: function() { return findTemplate('PhonePartnerList');},
        PhonePartnerProfile: function() { return findTemplate('PhonePartnerProfile');},
        ContactListPhone: function() { return findTemplate('ContactListPhone');},
        CreateReferralForm: function() { return findTemplate('CreateReferralForm');},
        BooleanField : function() { return  findTemplate('BooleanField');},
        ReferralSentConfirmation: function() { return findTemplate('ReferralSentConfirmation');},
        ViewReferralForm: function() { return findTemplate('ViewReferralForm');},
        ReferralMenuTemplate: function() { return findTemplate('ReferralMenuTemplate');},
        InBoxList: function() { return findTemplate('InBoxList');},
        AcceptReferralConfirmation: function() { return findTemplate('AcceptReferralConfirmation');},
        ConfirmReferralConfirmation: function() { return findTemplate('ConfirmReferralConfirmation');},
        ConvertReferralConfirmation: function() { return findTemplate('ConvertReferralConfirmation');},
        ArchiveReferralConfirmation: function() { return findTemplate('ArchiveReferralConfirmation');},
        UnArchiveReferralConfirmation: function() { return findTemplate('UnArchiveReferralConfirmation');},
        NoRecordForm: function() { return findTemplate('NoRecordForm');},
        NoRecordViewBar: function() { return findTemplate('NoRecordViewBar');},
        OutBoxList: function() { return findTemplate('OutBoxList');},
        OutBoxReferralForm: function() { return findTemplate('OutBoxReferralForm');},
        PhotoGalleryThumbs: function() { return findTemplate('PhotoGalleryThumbs');},
        PhotoGalleryShow: function() { return  findTemplate('PhotoGalleryShow');},
        ProfileDisplayView: function() { return findTemplate('ProfileDisplayView');},
        Testimonials: function() { return findTemplate('Testimonials');},
        LinkedInProfile: function() { return findTemplate('LinkedInProfile');},
        TestimonialsDisplay: function() { return findTemplate('TestimonialsDisplay');},
        PhotoGalleryThumbsNoEdit: function() { return findTemplate('PhotoGalleryThumbsNoEdit');},
        MasterTwoDetail: function() { return findTemplate('MasterTwoDetail');},
        PartnerReferralInbox: function() { return findTemplate('PartnerReferralInbox');},
        PartnerReferralOutbox: function() { return findTemplate('PartnerReferralOutbox');},
        HiddenField: function() { return findTemplate('HiddenField');},
        ProfilePrintView: function() { return findTemplate('ProfilePrintView');},
        ReferralProspectSummaryForm: function() { return findTemplate('ReferralProspectSummaryForm');},
        MashupView: function() { return findTemplate('MashupView');},
        MultiColumnList: function() { return  findTemplate('MultiColumnList');},
        StdMDMCView : function() { return  findTemplate('StdMDMCView');},
        LNRadioList: function() { return findTemplate('LNRadioList');},
        ProfileNavigation: function() { return findTemplate('ProfileNavigation');},
        LeftNavSummaryDetailView: function() { return findTemplate('LeftNavSummaryDetailView');},
        LeftNavMDMCView: function() { return findTemplate('LeftNavMDMCView');},
        PickCreateForm: function() { return findTemplate('PickCreateForm');},
        changePasswordTemplate: function() { return findTemplate('changePasswordTemplate');},
        PasswordField: function() { return findTemplate('PasswordField');},
        changePaypalIDTemplate : function() { return  findTemplate('changePaypalIDTemplate');},
        contextHelp: function() { return findTemplate('contextHelp');},
        PhonePickContactList: function() { return findTemplate('PhonePickContactList');},
        PhoneUpsertForm: function() { return findTemplate('CreateReferralCustomQ');},
        CreateReferralCustomQ: function() { return findTemplate('CreateReferralCustomQ');},
        PhoneStdView: function() { return findTemplate('PhoneStdView');},
        PhonePageNoViewBar: function() { return findTemplate('PhonePageNoViewBar');},
        PhoneStdForm: function() { return findTemplate('PhoneStdForm');},
        PhoneStdFormRefer: function() { return findTemplate('PhoneStdFormRefer');},
        ContactList: function() { return findTemplate('ContactList');},
        PhoneAppletMenu: function() { return findTemplate('PhoneAppletMenu');},
        PhonePageUpsert: function() { return findTemplate('PhonePageUpsert');},
        CompositeTextField: function() { return findTemplate('CompositeTextField');},
        pickFieldComposite: function() { return findTemplate('pickFieldComposite');},
        ConfirmDelete: function() { return findTemplate('ConfirmDelete');},
        ConfirmImport: function() { return findTemplate('ConfirmImport');},
        ConfirmBilling: function() { return findTemplate('ConfirmBilling');},
        Eula : function() { return  findTemplate('Eula');},
        ListSectionDetailView: function() { return findTemplate('ListSectionDetailView');},
        CollapseForm: function() { return findTemplate('CollapseForm');},
        StdFormNarrow: function() { return findTemplate('StdFormNarrow');},
        ImportProgress: function() { return findTemplate('ImportProgress');},
        TestimonialsQuoteEdit: function() { return findTemplate('TestimonialsQuoteEdit');},
        WizardUpsertForm: function() { return findTemplate('WizardUpsertForm');},
        WizardUpsertView: function() { return findTemplate('WizardUpsertView');},
        EnrichProgress: function() { return findTemplate('EnrichProgress');},
        CSVExportProgress: function() { return findTemplate('CSVExportProgress');},
        ConfirmEnrich: function() { return findTemplate('ConfirmEnrich');},
        CreateReferralWizardForm: function() { return findTemplate('CreateReferralWizardForm');},
        RadioButtons: function() { return findTemplate('RadioButtons');},
        MultiCheckBoxes:function() { return findTemplate('MultiCheckBoxes');},
        MultiCheckBoxes_Search:function() { return findTemplate('MultiCheckBoxes_Search');},
        WizardUpsertFormNarrow: function() { return findTemplate('WizardUpsertFormNarrow');},
        WizardUpsertFormNarrowRefType: function() { return findTemplate('WizardUpsertFormNarrowRefType');},
        CreateReferralWizardFormP2P: function() { return findTemplate('CreateReferralWizardFormP2P');},
        ReferralInboxP2P: function() { return findTemplate('ReferralInboxP2P');},
        ReferralInboxInvite: function() { return findTemplate('ReferralInboxInvite');},
        ReferralOutboxP2P: function() { return findTemplate('ReferralOutboxP2P');},
        ReferralOutboxInvite: function() { return findTemplate('ReferralOutboxInvite');},
        ViewReferralFormP2P: function() { return findTemplate('ViewReferralFormP2P');},
        AcceptReferralConfirmationNoArch: function() { return findTemplate('AcceptReferralConfirmationNoArch');},
        ViewReferralFormUnreadProspect: function() { return findTemplate('ViewReferralFormUnreadProspect');},
        ReferralViewBarTemplate: function() { return findTemplate('ReferralViewBarTemplate');},
        ViewReferralFormInvite: function() { return findTemplate('ViewReferralFormInvite');},
        OutBoxReferralFormP2P: function() { return findTemplate('OutBoxReferralFormP2P');},
        OutBoxReferralFormInvite: function() { return findTemplate('OutBoxReferralFormInvite');},
        PartnerReferralInboxP2P: function() { return findTemplate('PartnerReferralInboxP2P');},
        PartnerReferralInboxInvite: function() { return findTemplate('PartnerReferralInboxInvite');},
        PartnerReferralOutBoxP2P: function() { return findTemplate('PartnerReferralOutBoxP2P');},
        PartnerReferralOutBoxInvite: function() { return findTemplate('PartnerReferralOutBoxInvite');},
        ContactListPrivate: function() { return findTemplate('ContactListPrivate');},
        StdFormContact: function() { return findTemplate('StdFormContact');},
        StdFormPartner: function() { return findTemplate('StdFormPartner');},
        StdFormContactPartner: function() { return findTemplate('StdFormContactPartner');},
        ContactListPrivatePhone: function() { return findTemplate('ContactListPrivatePhone');},
        PhoneStdFormContact: function() { return findTemplate('PhoneStdFormContact');},
        CollapseFormNarrow: function() { return findTemplate('CollapseFormNarrow');},
        PhonePageUpsertNext: function() { return findTemplate('PhonePageUpsertNext');},
        PhoneStdFormContactPartner: function() { return findTemplate('PhoneStdFormContactPartner');},
        UpsertFormNarrow: function() { return findTemplate('UpsertFormNarrow');},
        AllMembersList: function() { return findTemplate('AllMembersList');},
        StdFormNarrowPub: function() { return findTemplate('StdFormNarrowPub');},
        StdFormMember: function() { return findTemplate('StdFormMember');},
        PhoneStdMember: function() { return findTemplate('PhoneStdMember');},
        PhoneMemberProfile: function() { return findTemplate('PhoneMemberProfile');},
        PhoneMemberList: function() { return findTemplate('PhoneMemberList');},
        InvitationSentConfirmation: function() { return findTemplate('InvitationSentConfirmation');},
        MessageSentConfirmation: function() { return findTemplate('MessageSentConfirmation');},
        PhoneStdViewList: function() { return findTemplate('PhoneStdViewList');},
        StdFormPlain: function() { return findTemplate('StdFormPlain');},
        WizardUpsertViewShopping: function() { return findTemplate('WizardUpsertViewShopping');},
        RecommendationsList: function() { return findTemplate('RecommendationsList');},
        MasterDetailViewNarrow: function() { return findTemplate('MasterDetailViewNarrow');},
        SpecialtiesMasterPartner: function() { return findTemplate('SpecialtiesMasterPartner');},
        WebNavPanel: function() { return findTemplate('WebNavPanel');},
        SecondTierNavBar: function() { return findTemplate('SecondTierNavBar');},
        DashBoard: function() { return findTemplate('DashBoard');},
        RecommendationsListUser: function() { return findTemplate('RecommendationsListUser');},
        SpecialtiesMasterUser: function() { return findTemplate('SpecialtiesMasterUser');},
        StdSummaryChartView: function() { return findTemplate('StdSummaryChartView');},
        LeftNavSummaryChartView: function() { return findTemplate('LeftNavSummaryChartView');},
        ContactActionBarTemplate: function() { return findTemplate('ContactActionBarTemplate');},
        RadioButtonsDynamic: function() { return findTemplate('RadioButtonsDynamic');},
        PlainForm: function() { return findTemplate('PlainForm');},
        CriteriaMapList: function() { return findTemplate('CriteriaMapList');},
        ChapterList: function() { return findTemplate('ChapterList');},
        ChapterDisplayView: function() { return findTemplate('ChapterDisplayView');},
        ChapterHomeForm: function() { return findTemplate('ChapterHomeForm');},
        ChapterFormNarrow: function() { return findTemplate('ChapterFormNarrow');},
        ChapterMemberList: function() { return findTemplate('ChapterMemberList');},
        PhoneChapterList: function() { return findTemplate('PhoneChapterList');},
        PhoneChapterProfile: function() { return findTemplate('PhoneChapterProfile');},
        PhoneChapterMaster: function() { return findTemplate('PhoneChapterMaster');},
        PhoneMasterDetailView: function() { return findTemplate('PhoneMasterDetailView');},
        PhoneNavPanel: function() { return findTemplate('PhoneNavPanel');},
        StdTiles: function() { return findTemplate('StdTiles');},
        STN_phonehome: function() { return findTemplate('STN_phonehome');},
        EventList: function() { return findTemplate('EventList');},
        TimeField: function() { return findTemplate('TimeField');},
        EventExpectedExpandList: function() { return findTemplate('EventExpectedExpandList');},
        AttendenceChart: function() { return findTemplate('AttendenceChart');},
        ChapterDashBoardView: function() { return findTemplate('ChapterDashBoardView');},
        ListMapView: function() { return findTemplate('ListMapView');},
        EventFormNarrow: function() { return findTemplate('EventFormNarrow');},
        AttendeeMember: function() { return findTemplate('AttendeeMember');},
        CheckedInConfirmation_Self: function() { return findTemplate('CheckedInConfirmation_Self');},
        CheckedInConfirmation_Other: function() { return findTemplate('CheckedInConfirmation_Other');},
        CheckedOutConfirmation_Other: function() { return findTemplate('CheckedOutConfirmation_Other');},
        StdExpandableChildList: function() { return findTemplate('StdExpandableChildList');},
        LinkedInTiles : function() { return  findTemplate('LinkedInTiles');},
        STN_HomePageView : function() { return  findTemplate('STN_HomePageView');},
        STN_BannerMessage: function() { return findTemplate('STN_BannerMessage');},
        STN_WebNavPanel: function() { return findTemplate('STN_WebNavPanel');},
        QualificationsForm: function() { return findTemplate('QualificationsForm');},
        QualificationsFormDisplay: function() { return findTemplate('QualificationsFormDisplay');},
        ProfileDisplayMapView: function() { return findTemplate('ProfileDisplayMapView');},
        BasicForm: function() { return findTemplate('BasicForm');},
        AddGuestConfirmation: function() { return findTemplate('AddGuestConfirmation');},
        ChapterDashBoardViewChart: function() { return findTemplate('ChapterDashBoardViewChart');},
        STN_StdFormContactPartner: function() { return findTemplate('STN_StdFormContactPartner');},
        STN_PhoneHomePageTitleSummary:function() { return findTemplate('STN_PhoneHomePageTitleSummary');},
        PhoneContextNavPanel: function() { return findTemplate('PhoneContextNavPanel');},
        ConfirmJoinChapter: function() { return findTemplate('ConfirmJoinChapter');},
        AttendeeMemberNoAct: function() { return findTemplate('AttendeeMemberNoAct');},
        STN_speakerInviteMessage: function() { return findTemplate('STN_speakerInviteMessage');},
        SpeakersList: function() { return findTemplate('SpeakersList');},
        SpeakerForm: function() { return findTemplate('SpeakerForm');},
        STN_HomePageUserProfile: function() { return findTemplate('STN_HomePageUserProfile');},
        STN_EventHomeList: function() { return findTemplate('STN_EventHomeList');},
        STN_HomePageTitleSummary: function() { return findTemplate('STN_HomePageTitleSummary');},
        STN_HomePageReferralStats: function() { return findTemplate('STN_HomePageReferralStats');},
        InvitedMemberList: function() { return findTemplate('InvitedMemberList');},
        CheckedInInvalid: function() { return findTemplate('CheckedInInvalid');},
        DateTimeField: function() { return findTemplate('DateTimeField');},
        STN_ChapterListDetailView: function() { return findTemplate('STN_ChapterListDetailView');},
        WizardAssocSnippet: function() { return findTemplate('WizardAssocSnippet');},
        CheckedInPositionError: function() { return findTemplate('CheckedInPositionError');},
        LeftNavSummaryDetailViewIFrame: function() { return findTemplate('LeftNavSummaryDetailViewIFrame');},
        PhoneEventMaster: function() { return findTemplate('PhoneEventMaster');},
        SpeakerFormNarrow: function() { return findTemplate('SpeakerFormNarrow');},
        speakerEventList: function() { return findTemplate('speakerEventList');},
        UpdateStatusConfirmation: function() { return findTemplate('UpdateStatusConfirmation');},
        UpdateStatusConfirmationDone: function() { return findTemplate('UpdateStatusConfirmationDone');},
        AcceptInvitationConfirmation: function() { return findTemplate('AcceptInvitationConfirmation');},
        WizardUpsertFormRefStatus: function() { return findTemplate('WizardUpsertFormRefStatus');},
        ForwardReferralWizardForm: function() { return findTemplate('ForwardReferralWizardForm');},
        WizardUpsertFormRefStatusConfirm: function() { return findTemplate('WizardUpsertFormRefStatusConfirm');},
        LeftSecondTierNavSummaryDetailView: function() { return findTemplate('LeftSecondTierNavSummaryDetailView');},
        LeaderboardMade: function() { return findTemplate('LeaderboardMade');},
        SearchView: function() { return findTemplate('SearchView');},
        SearchForm: function() { return findTemplate('SearchForm');},
        ConfirmSS_Save_Prompt : function() { return findTemplate('ConfirmSS_Save_Prompt');},
        ConfirmSS_Save: function() { return findTemplate('ConfirmSS_Save');},
        ConfirmSS_Delete: function() { return findTemplate('ConfirmSS_Delete');},
        ConfirmSS_Hide: function() { return findTemplate('ConfirmSS_Hide');},
        AwardList: function() { return findTemplate('AwardList');},
        BusinessHomeForm: function() { return findTemplate('BusinessHomeForm');},
        EmailTemplateForm: function() { return findTemplate('EmailTemplateForm');},
        ImageForm: function() { return findTemplate('ImageForm');},
        ImageList: function() { return findTemplate('ImageList');},
        SpeakerStatsFormNarrow: function() { return findTemplate('SpeakerStatsFormNarrow');},
        SpeakerSummaryChartView: function() { return findTemplate('SpeakerSummaryChartView');},
        RatingStarField: function() { return findTemplate('RatingStarField');},
        AllEventList: function() { return findTemplate('AllEventList');},
        EventFormAll: function() { return findTemplate('EventFormAll');},
        ConfirmJoinMeeting: function() { return findTemplate('ConfirmJoinMeeting');},
        ConfirmLeaveMeeting: function() { return findTemplate('ConfirmLeaveMeeting');},
        BusinessDirectoryHome: function() {return findTemplate('BusinessDirectoryHome');},
        ListMapViewBizDirectory: function(){return findTemplate('ListMapViewBizDirectory');},
        BusDirectoryDetailForm: function(){return findTemplate('BusDirectoryDetailForm');},
        ListViewBizDirectory: function(){return findTemplate('ListViewBizDirectory');},
        BusinessDirectoryList: function(){return findTemplate('BusinessDirectoryList');},
        BusinessDirectoryEditView: function(){return findTemplate('BusinessDirectoryEditView');},
        PartyThumbNailTile: function(){return findTemplate('PartyThumbNailTile');},
        ConfirmBusSearchZip: function(){return findTemplate('ConfirmBusSearchZip');},
        MyEventList: function(){return findTemplate('MyEventList');},
        BusinessPickList: function(){return findTemplate('BusinessPickList');},
        LeaderBoardSummaryDetailView: function(){return findTemplate('LeaderBoardSummaryDetailView');},
        LeaderBoardFormLikeMe: function(){return findTemplate('LeaderBoardFormLikeMe');},
        LeaderBoardFormPowerPartners: function(){return findTemplate('LeaderBoardFormPowerPartners');},
        PhoneEventFormNarrow: function(){return findTemplate('PhoneEventFormNarrow');},
        PhoneAllEventList: function(){return findTemplate('PhoneAllEventList');},
        PhoneMeetingAttendeeList: function(){return findTemplate('PhoneMeetingAttendeeList');},
        PhoneMeetingAttendeeListNoAct: function(){return findTemplate('PhoneMeetingAttendeeListNoAct');},
        OutBox3rdPartnerList: function(){return findTemplate('OutBox3rdPartnerList');},
        ContactListNoRelation: function(){return findTemplate('ContactListNoRelation');},
        ContactListNoRelationPhone: function(){return findTemplate('ContactListNoRelationPhone');},
        MasterDetailSearchListView: function(){return findTemplate('MasterDetailSearchListView');},
        AttendeeFloater: function(){return findTemplate('AttendeeFloater');},
        AttendeeNewGuest: function(){return findTemplate('AttendeeNewGuest');},
        AttendeeFloaterNoAct: function(){return findTemplate('AttendeeFloaterNoAct');},
        AttendeeNewGuestNoAct: function(){return findTemplate('AttendeeNewGuestNoAct');},
        PhoneMemberListPP: function(){return findTemplate('PhoneMemberListPP');},
        STN_PhoneEventHomeList: function(){return findTemplate('STN_PhoneEventHomeList');},
        STN_MissingInfo: function(){return findTemplate('STN_MissingInfo');},
        STN_BoxScoreNewMembers: function(){return findTemplate('STN_BoxScoreNewMembers');},
        STN_BoxScoreNewPowerPartners: function(){return findTemplate('STN_BoxScoreNewPowerPartners');},
        ChapterMeetingAttendeeListNoAct: function(){return findTemplate('ChapterMeetingAttendeeListNoAct');},
        PowerCenterListDetailView: function(){return findTemplate('PowerCenterListDetailView');},
        MembersDrillList: function(){return findTemplate('MembersDrillList');},
        BadgeInlineScore: function(){return findTemplate('BadgeInlineScore');},
        BadgeInlineRole: function(){return findTemplate('BadgeInlineRole');},
        BadgeInvitations: function(){return findTemplate('BadgeInvitations');},
        BadgeAttendance: function(){return findTemplate('BadgeAttendance');},
        BadgeReferrals: function(){return findTemplate('BadgeReferrals');},

        BadgeLeadAmbassador: function(){return findTemplate('BadgeLeadAmbassador');},
        BadgeAssociateAmbassador: function(){return findTemplate('BadgeAssociateAmbassador');},
        BadgeGenius: function(){return findTemplate('BadgeGenius');},
        AllMembersListBadges: function(){return findTemplate('AllMembersListBadges');},
        PhoneMemberListBadges: function(){return findTemplate('PhoneMemberListBadges');},
        PhoneMemberProfileBadges: function(){return findTemplate('PhoneMemberProfileBadges');},
        StdFormMemberBadges: function(){return findTemplate('StdFormMemberBadges');},
        STN_HomePageMyBadges: function(){return findTemplate('STN_HomePageMyBadges');},
        STN_BoxScoreWebProfileHits: function(){return findTemplate('STN_BoxScoreWebProfileHits');},
        ReferralInboxMessage: function(){return findTemplate('ReferralInboxMessage');},
        ReferralOutboxMessage: function(){return findTemplate('ReferralOutboxMessage');},
        ReferralInboxAnnouncement: function(){return findTemplate('ReferralInboxAnnouncement');},
        BadgeRegionalAmbassador: function(){return findTemplate('BadgeRegionalAmbassador');},
      };
            
      return baseTemplates;
      
      
});
